sudo: required

language: ruby

services:
  - docker

rvm:
  - 2.3

script:
  "bundle exec rspec"

notifications:
  email:
    recipients:
      - moorer@udel.edu
    on_success: change
    on_failure: always
